receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
  otlp/jaeger:
    endpoint: jaeger:4317 # GRPC
    tls:
      insecure: true # WARNING: set to `false` in production

service:
  pipelines:
    traces/dev:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/jaeger]
